version: '3'
services:
  api:
    image: sample-express-app
    container_name: api
    build: ./api
    networks:
      - backend
    ports:
      - "3000:3000"
    depends_on:
      - redis
  
  redis:
    image: redis
    container_name: redis
    networks:
      - backend

networks:
  backend:
    driver: bridge